all:
  vars:
    sudo: yes
    ansible_connection: ssh
    ansible_ssh_user: ubuntu
    ansible_become: true
    security_mode: plaintext
    ansible_python_interpreter: /usr/bin/python3
preflight:
  hosts:
    10.2.5.90:
    10.2.5.189:
    10.2.5.77:
    10.2.5.196:
    10.2.5.105:
    10.2.5.144:
    10.2.5.215:
ssl_CA:
  hosts:
    10.2.5.90:
zookeeper:
  hosts:
    10.2.5.90:
    10.2.5.189:
    10.2.5.77:
broker:
  hosts:
    10.2.5.90:
      kafka:
        broker:
          id: 1
    10.2.5.189:
      kafka:
        broker:
          id: 2
    10.2.5.77:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    10.2.5.215:
control-center:
  hosts:
    10.2.5.196:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 10.2.5.105:8083
connect-distributed:
  hosts:
    10.2.5.105:
kafka-rest:
  hosts:
    10.2.5.105:
ksql:
  hosts:
    10.2.5.144:
tools:
  hosts:
    10.2.5.90:

