all:
  vars:
    sudo: yes
    ansible_connection: ssh
    ansible_ssh_user: ubuntu
    ansible_become: true
    security_mode: plaintext
    ansible_python_interpreter: /usr/bin/python3
preflight:
  hosts:
    10.2.5.227:
    10.2.5.152:
    10.2.5.175:
    10.2.5.163:
    10.2.5.131:
    10.2.5.87:
    10.2.5.198:
ssl_CA:
  hosts:
    10.2.5.227:
zookeeper:
  hosts:
    10.2.5.227:
    10.2.5.152:
    10.2.5.175:
broker:
  hosts:
    10.2.5.227:
      kafka:
        broker:
          id: 1
    10.2.5.152:
      kafka:
        broker:
          id: 2
    10.2.5.175:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    10.2.5.198:
control-center:
  hosts:
    10.2.5.163:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 10.2.5.131:8083
connect-distributed:
  hosts:
    10.2.5.131:
kafka-rest:
  hosts:
    10.2.5.131:
ksql:
  hosts:
    10.2.5.87:
tools:
  hosts:
    10.2.5.227:

